database: hsqldb

# Database Settings
spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=mysql;
    username: sa
    password:
    driverClassName: org.h2.Driver

  # H2 Settings
  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      schema-locations: classpath*:/${database}/schema.sql
      data-locations: classpath*:/${database}/data.sql
      platform: h2
      mode: embedded

  # jpa setting
  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        show_sql: true

    open-in-view: false

 # logging setting
  logging:
    level:
      org:
        springframework.web: debug

  # redis
  redis:
    host: localhost
    port: 6379
